make:
	gcc -o wish wish.c -Wall -Werror -g
run:
	./wish

readfile:
	gcc -o readfile readfile.c -Wall -Werror -g

fork:
	gcc -o fork_ fork.c -Wall -Werror -g

test:
	~cs537-1/tests/bin/test-wish.csh -v -c
